#!/bin/bash

# Reset
NO_COLOR='\033[0m'       # Text Reset
RED='\033[1;31m'         # Red Bold


protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    read -p "$(echo -e "⛔  - You're about to push $RED$protected_branch$NO_COLOR and break production. Are you willing to take the risk? [y|n] " )" -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi